server:
  port: 8081

spring:
  #  로컬 db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itdadb
    username: itda
    password: itda1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true


  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    mvc:
      static-path-pattern: "/static/**"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace